name: 'Saber Task Dev API'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]